### ISSUE TITLE
10.1 Error

### ISSUE THREAD

**Issue by VaporAPX** [Repooc/ElvUI_RatioMinimapAuras#2]
Hi there, I get the following error in 10.1 with the addon enabled. 

`7x ...aries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua:110: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name ElvUI_RatioAuras. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua"]:110: in function `RegisterPlugin'
[string "@ElvUI_RatioMinimapAuras/Auras.lua"]:144: in function <ElvUI_RatioMinimapAuras/Auras.lua:140>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAPI'
[string "@ElvUI/Core/General/Core.lua"]:1968: in function <ElvUI/Core/General/Core.lua:1939>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:265: in function <ElvUI/Core/init.lua:264>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@!KalielsTracker/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...s/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:754: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = "ElvUI_RatioAuras"
(*temporary) = "Title"
(*temporary) = "Invalid AddOn name ElvUI_RatioAuras. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"
`

**Comment by Repooc** [comment]
already fixed in the dev build
