### ISSUE TITLE
lua erorr 

### ISSUE THREAD

**Issue by PaWell71** [Repooc/ElvUI_RatioMinimapAuras#3]
Hi, i just installed ElvUI RatioMinimapAuras plugin and when I entered the game it was already working incorrectly. Auras appear only if you change the size or indentation, the number of buffs per line and the number of lines do not correspond to the settings in ElvUI. After the reboot, all the settings are reset and the auras are hidden 

Message: Interface/FrameXML/SecureGroupHeaders.lua:725: CreateFrame(): Couldn't find inherited node "ElvUIAuraTemplate3526"
Time: Fri Sep 22 01:27:53 2023
Count: 1
Stack: Interface/FrameXML/SecureGroupHeaders.lua:725: CreateFrame(): Couldn't find inherited node "ElvUIAuraTemplate3526"
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/FrameXML/SecureGroupHeaders.lua"]:725: in function <Interface/FrameXML/SecureGroupHeaders.lua:724>
[string "@Interface/FrameXML/SecureGroupHeaders.lua"]:762: in function <Interface/FrameXML/SecureGroupHeaders.lua:735>
[string "@Interface/FrameXML/SecureGroupHeaders.lua"]:1074: in function <Interface/FrameXML/SecureGroupHeaders.lua:961>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/ElvUI/Core/Modules/Auras/Auras.lua"]:522: in function `CreateAuraHeader'
[string "@Interface/AddOns/ElvUI/Core/Modules/Auras/Auras.lua"]:555: in function <Interface/AddOns/ElvUI/Core/Modules/Auras/Auras.lua:527>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1813: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1828: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1854: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1964: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1933>
...
[string "@Interface/FrameXML/UIParent.lua"]:547: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = "Button"
(*temporary) = "ElvUIPlayerBuffsAuraButton1"
(*temporary) = ElvUIPlayerBuffs {
 0 = <userdata>
 enchants = <table> {
 }
 auraType = "buffs"
 name = "ElvUIPlayerBuffs"
 spells = <table> {
 }
 visibility = Frame {
 }
 filter = "HELPFUL"
}
(*temporary) = "ElvUIAuraTemplate3526"

![screenshot](https://i.imgur.com/bgr8FEa.jpeg)

**Comment by Repooc** [comment]
sorry was busy but had updated it to now support the full range of sizes that elvui supported which is 10-60 and have no need to be even numbers now
